### ISSUE TITLE
Sound Event contains IDs unknown to the receiver!

### ISSUE THREAD

**Issue by VieLassiel** [TeamMidnightDust/Decorative#7]
Everything was running great on the server, I have 4 people playing on it, one of the players placed down a ceiling fan from this mod and since that moment if anyone was to get disconnected or had to relog for any reason, they found them selves unable to rejoin the server and was presented with the following error:

Connection Lost
Registry remapping failed: Received ID map for minecraft:sound_Event contains IDs unknown to the receiver!
- decorative:ceiling_fan.ambient

![Discord_jWskiGrHG8](https://user-images.githubusercontent.com/5722595/100453031-e8399600-307f-11eb-8414-5ae8990ac00e.png)

I can not find anything helpful related to this error.

I'm playing on 1.16.3

EDIT: I want to note that disabling this mod, starting the server, then re-enabling it and restarting the server so that it removes all items from the mod, will allow you to join the server while the mod is still installed, just don't place down the fan.. I haven't tested it past this point, but thought it was worth noting for anyone who may not know.

**Comment by Motschen** [comment]
That seems really weird, no plan what could be causing this tbh.

**Comment by kafkakhalis17** [comment]
this is happening to me too

**Comment by Motschen** [comment]
I think I might have fixed it, could you try this version: https://drive.google.com/file/d/1b44Ki_P78NMiH1PCng-CHWLYL61ydHHp/view?usp=sharing
Also, this version has some nice new features, so maybe you could provide some feedback if you want ;)

**Comment by tealtoxic** [comment]
bumped.

**Comment by Motschen** [comment]
Well, could you test with the build in the message above your message?

**Comment by Motschen** [comment]
Fixed in v4.0.0
