### ISSUE TITLE
Springboards generate duplicates when placed

### ISSUE THREAD

**Issue by EvieTheOwl** [TeamMidnightDust/Decorative#9]
![2021-06-09_18 15 57](https://user-images.githubusercontent.com/46009144/121399960-ea45b100-c94e-11eb-8350-7bda65f8a7b6.png)
As seen above when you place a springboard it generates a duplicate of it in the opposite direction, they overlap. This essentially means you can dupe springboards :P

**Comment by EvieTheOwl** [comment]
Testing on AOF4s experimental 1.17 pack for version 4.1.0

**Comment by Motschen** [comment]
I've identified the issue, will push a new build in a few minutes.
